"""
Module 4 — Adaptive Question Engine
Maintains a concept graph and generates probing questions
that target the user's weak areas. Difficulty adapts based on performance.
"""

import json
from gemini_client import call_gemini
from prompts.adaptive_questions import CONCEPT_GRAPH_PROMPT, ADAPTIVE_QUESTION_PROMPT


class AdaptiveEngine:
    """
    Tracks concept mastery and generates targeted probing questions.
    Uses a concept graph (generated by Gemini at session start) to
    identify what the user knows, what they've avoided, and what to probe next.
    """

    def __init__(self):
        self.concept_graph = {}          # Generated at session start
        self.demonstrated = set()        # Concept IDs user has shown understanding of
        self.weak = set()                # Concept IDs user handled poorly
        self.unaddressed = set()         # Concept IDs never touched
        self.performance_scores = []     # Rolling performance (0-1 per turn)
        self.questions_asked = []        # History of probing questions

    def initialize_concept_graph(self, topic: str) -> dict:
        """Generate the topic's concept graph using Gemini at session start."""
        prompt = CONCEPT_GRAPH_PROMPT.format(topic=topic)
        self.concept_graph = call_gemini(prompt, expect_json=True)

        # Initialize all concepts as unaddressed
        for concept in self.concept_graph.get("concepts", []):
            self.unaddressed.add(concept["id"])

        return self.concept_graph

    def update_concept_coverage(self, parsed_argument: dict, weakness_scores: dict):
        """
        After each user turn, update which concepts they've demonstrated
        understanding of and which they've handled weakly.
        """
        # This will be enhanced with smarter concept-matching logic
        # For now, uses Gemini to map argument content to concept IDs
        pass

    def get_performance_level(self) -> str:
        """Calculate current performance level from rolling scores."""
        if not self.performance_scores:
            return "basic"

        avg = sum(self.performance_scores) / len(self.performance_scores)
        if avg < 0.3:
            return "struggling"
        elif avg < 0.5:
            return "basic"
        elif avg < 0.7:
            return "competent"
        elif avg < 0.9:
            return "strong"
        else:
            return "expert"

    def generate_probing_question(
        self,
        topic: str,
        debate_history: list,
        fallacies_committed: list,
    ) -> dict:
        """
        Generate a targeted probing question based on current concept coverage.

        Returns:
            dict with: question, target_concept, difficulty, rationale
        """
        prompt = ADAPTIVE_QUESTION_PROMPT.format(
            topic=topic,
            concept_graph=json.dumps(self.concept_graph, indent=2),
            demonstrated_concepts=json.dumps(list(self.demonstrated)),
            weak_concepts=json.dumps(list(self.weak | self.unaddressed)),
            fallacies_committed=json.dumps(fallacies_committed),
            performance_level=self.get_performance_level(),
            debate_history=json.dumps(debate_history[-6:]),
        )

        result = call_gemini(prompt, expect_json=True)
        self.questions_asked.append(result)
        return result

    def record_response_quality(self, score: float):
        """Record a 0-1 score for the user's response to a probing question."""
        self.performance_scores.append(score)

    def get_mastery_summary(self) -> dict:
        """Return a summary of concept coverage for the mastery evaluator."""
        return {
            "demonstrated_strongly": list(self.demonstrated),
            "demonstrated_weakly": list(self.weak),
            "never_addressed": list(self.unaddressed),
            "performance_level": self.get_performance_level(),
            "questions_asked": self.questions_asked,
        }
